/* Generated By:JJTree&JavaCC: Do not edit this line. CMMParserConstants.java */
package cmm.javacc.zck;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMMParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EMPTY = 1;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int CONTINUE = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int REAL = 21;
  /** RegularExpression Id. */
  int CHAR = 22;
  /** RegularExpression Id. */
  int VOID = 23;
  /** RegularExpression Id. */
  int LCB = 24;
  /** RegularExpression Id. */
  int RCB = 25;
  /** RegularExpression Id. */
  int SEMI = 26;
  /** RegularExpression Id. */
  int LRB = 27;
  /** RegularExpression Id. */
  int RRB = 28;
  /** RegularExpression Id. */
  int ASN = 29;
  /** RegularExpression Id. */
  int LSB = 30;
  /** RegularExpression Id. */
  int RSB = 31;
  /** RegularExpression Id. */
  int LT = 32;
  /** RegularExpression Id. */
  int LTE = 33;
  /** RegularExpression Id. */
  int EQ = 34;
  /** RegularExpression Id. */
  int NEQ = 35;
  /** RegularExpression Id. */
  int GT = 36;
  /** RegularExpression Id. */
  int GTE = 37;
  /** RegularExpression Id. */
  int ADD = 38;
  /** RegularExpression Id. */
  int SUB = 39;
  /** RegularExpression Id. */
  int MUL = 40;
  /** RegularExpression Id. */
  int DIV = 41;
  /** RegularExpression Id. */
  int CMMA = 42;
  /** RegularExpression Id. */
  int LAND = 43;
  /** RegularExpression Id. */
  int BAND = 44;
  /** RegularExpression Id. */
  int LOR = 45;
  /** RegularExpression Id. */
  int BOR = 46;
  /** RegularExpression Id. */
  int BXOR = 47;
  /** RegularExpression Id. */
  int LNT = 48;
  /** RegularExpression Id. */
  int BNT = 49;
  /** RegularExpression Id. */
  int DEC = 50;
  /** RegularExpression Id. */
  int INC = 51;
  /** RegularExpression Id. */
  int MOD = 52;
  /** RegularExpression Id. */
  int ILT = 53;
  /** RegularExpression Id. */
  int RLT = 54;
  /** RegularExpression Id. */
  int DIGITS = 55;
  /** RegularExpression Id. */
  int CLT = 56;
  /** RegularExpression Id. */
  int SLT = 57;
  /** RegularExpression Id. */
  int ID = 58;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MATCH_NON_EMPTY = 1;
  /** Lexical state. */
  int WithinMultiComment = 2;
  /** Lexical state. */
  int WithinLineComment = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"//\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<token of kind 13>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"int\"",
    "\"real\"",
    "\"char\"",
    "\"void\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\"&&\"",
    "\"&\"",
    "\"||\"",
    "\"|\"",
    "\"^\"",
    "\"!\"",
    "\"~\"",
    "\"--\"",
    "\"++\"",
    "\"%\"",
    "<ILT>",
    "<RLT>",
    "<DIGITS>",
    "<CLT>",
    "<SLT>",
    "<ID>",
  };

}
