/* Generated By:JavaCC: Do not edit this line. CMMParserTreeConstants.java Version 5.0 */
package cmm.javacc.zck;

public interface CMMParserTreeConstants
{
  public int JJTSENTENCES = 0;
  public int JJTEMPTY = 1;
  public int JJTSENTENCE = 2;
  public int JJTFUNCPARAMBRACKETEXPR = 3;
  public int JJTFUNCPARAMCOMMAEXPR = 4;
  public int JJTFUNCPARAMEXPR = 5;
  public int JJTDECLCOMMAEXPR = 6;
  public int JJTDECLEXPR = 7;
  public int JJTTYPE = 8;
  public int JJTLITERAL = 9;
  public int JJTCOMMAEXPR = 10;
  public int JJTASSIGNEXPR = 11;
  public int JJTLOGICOREXPR = 12;
  public int JJTLOGICANDEXPR = 13;
  public int JJTBITOREXPR = 14;
  public int JJTBITEXOREXPR = 15;
  public int JJTBITANDEXPR = 16;
  public int JJTRELEXPR = 17;
  public int JJTRELOP = 18;
  public int JJTADDSUBEXPR = 19;
  public int JJTADDSUBOP = 20;
  public int JJTMULDIVEXPR = 21;
  public int JJTMULDIVOP = 22;
  public int JJTUNARYEXPR = 23;
  public int JJTUNARYOP = 24;
  public int JJTPOSTUNARYEXPR = 25;
  public int JJTPOSTUNARYOP = 26;
  public int JJTBRACKETEXPR = 27;
  public int JJTDECLVAREXPR = 28;
  public int JJTDECLVARARRFUNCEXPR = 29;
  public int JJTDECLVARBRACKETEXPR = 30;
  public int JJTDECLTYPEEXPR = 31;
  public int JJTDECLTYPEARRFUNCEXPR = 32;
  public int JJTDECLTYPEBRACKETEXPR = 33;
  public int JJTSENTENCES_ = 34;
  public int JJTSENTENCE_ = 35;
  public int JJTFUNCPARAMBRACKETEXPR_ = 36;
  public int JJTFUNCPARAMCOMMAEXPR_ = 37;
  public int JJTFUNCPARAMEXPR_ = 38;
  public int JJTDECLCOMMAEXPR_ = 39;
  public int JJTDECLEXPR_ = 40;
  public int JJTTYPE_ = 41;
  public int JJTLITERAL_ = 42;
  public int JJTCOMMAEXPR_ = 43;
  public int JJTASSIGNEXPR_ = 44;
  public int JJTLOGICOREXPR_ = 45;
  public int JJTLOGICANDEXPR_ = 46;
  public int JJTBITOREXPR_ = 47;
  public int JJTBITEXOREXPR_ = 48;
  public int JJTBITANDEXPR_ = 49;
  public int JJTRELEXPR_ = 50;
  public int JJTRELOP_ = 51;
  public int JJTADDSUBEXPR_ = 52;
  public int JJTADDSUBOP_ = 53;
  public int JJTMULDIVEXPR_ = 54;
  public int JJTMULDIVOP_ = 55;
  public int JJTUNARYEXPR_ = 56;
  public int JJTUNARYOP_ = 57;
  public int JJTPOSTUNARYEXPR_ = 58;
  public int JJTPOSTUNARYOP_ = 59;
  public int JJTBRACKETEXPR_ = 60;
  public int JJTDECLVAREXPR_ = 61;
  public int JJTDECLVARARRFUNCEXPR_ = 62;
  public int JJTDECLVARBRACKETEXPR_ = 63;
  public int JJTDECLTYPEEXPR_ = 64;
  public int JJTDECLTYPEARRFUNCEXPR_ = 65;
  public int JJTDECLTYPEBRACKETEXPR_ = 66;
  public int JJTIF = 67;
  public int JJTELSE = 68;
  public int JJTWHILE = 69;
  public int JJTBREAK = 70;
  public int JJTCONTINUE = 71;
  public int JJTRETURN = 72;
  public int JJTINT = 73;
  public int JJTREAL = 74;
  public int JJTCHAR = 75;
  public int JJTVOID = 76;
  public int JJTLCB = 77;
  public int JJTRCB = 78;
  public int JJTSEMI = 79;
  public int JJTLRB = 80;
  public int JJTRRB = 81;
  public int JJTASN = 82;
  public int JJTLSB = 83;
  public int JJTRSB = 84;
  public int JJTLT = 85;
  public int JJTLTE = 86;
  public int JJTEQ = 87;
  public int JJTNEQ = 88;
  public int JJTGT = 89;
  public int JJTGTE = 90;
  public int JJTADD = 91;
  public int JJTSUB = 92;
  public int JJTMUL = 93;
  public int JJTDIV = 94;
  public int JJTCMMA = 95;
  public int JJTLAND = 96;
  public int JJTBAND = 97;
  public int JJTLOR = 98;
  public int JJTBOR = 99;
  public int JJTBXOR = 100;
  public int JJTLNT = 101;
  public int JJTBNT = 102;
  public int JJTDEC = 103;
  public int JJTINC = 104;
  public int JJTMOD = 105;
  public int JJTILT = 106;
  public int JJTRLT = 107;
  public int JJTCLT = 108;
  public int JJTSLT = 109;
  public int JJTID = 110;


  public String[] jjtNodeName = {
    "Sentences",
    "Empty",
    "Sentence",
    "FuncParamBracketExpr",
    "FuncParamCommaExpr",
    "FuncParamExpr",
    "DeclCommaExpr",
    "DeclExpr",
    "Type",
    "Literal",
    "CommaExpr",
    "AssignExpr",
    "LogicOrExpr",
    "LogicAndExpr",
    "BitOrExpr",
    "BitExOrExpr",
    "BitAndExpr",
    "RelExpr",
    "RelOp",
    "AddSubExpr",
    "AddSubOp",
    "MulDivExpr",
    "MulDivOp",
    "UnaryExpr",
    "UnaryOp",
    "PostUnaryExpr",
    "PostUnaryOp",
    "BracketExpr",
    "DeclVarExpr",
    "DeclVarArrFuncExpr",
    "DeclVarBracketExpr",
    "DeclTypeExpr",
    "DeclTypeArrFuncExpr",
    "DeclTypeBracketExpr",
    "Sentences_",
    "Sentence_",
    "FuncParamBracketExpr_",
    "FuncParamCommaExpr_",
    "FuncParamExpr_",
    "DeclCommaExpr_",
    "DeclExpr_",
    "Type_",
    "Literal_",
    "CommaExpr_",
    "AssignExpr_",
    "LogicOrExpr_",
    "LogicAndExpr_",
    "BitOrExpr_",
    "BitExOrExpr_",
    "BitAndExpr_",
    "RelExpr_",
    "RelOp_",
    "AddSubExpr_",
    "AddSubOp_",
    "MulDivExpr_",
    "MulDivOp_",
    "UnaryExpr_",
    "UnaryOp_",
    "PostUnaryExpr_",
    "PostUnaryOp_",
    "BracketExpr_",
    "DeclVarExpr_",
    "DeclVarArrFuncExpr_",
    "DeclVarBracketExpr_",
    "DeclTypeExpr_",
    "DeclTypeArrFuncExpr_",
    "DeclTypeBracketExpr_",
    "IF",
    "ELSE",
    "WHILE",
    "BREAK",
    "CONTINUE",
    "RETURN",
    "INT",
    "REAL",
    "CHAR",
    "VOID",
    "LCB",
    "RCB",
    "SEMI",
    "LRB",
    "RRB",
    "ASN",
    "LSB",
    "RSB",
    "LT",
    "LTE",
    "EQ",
    "NEQ",
    "GT",
    "GTE",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "CMMA",
    "LAND",
    "BAND",
    "LOR",
    "BOR",
    "BXOR",
    "LNT",
    "BNT",
    "DEC",
    "INC",
    "MOD",
    "ILT",
    "RLT",
    "CLT",
    "SLT",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=2160690f636945df978d1f8d1bb0ea63 (do not edit this line) */
